### ISSUE TITLE
Separate the lazy loading logic from viewport logic

### ISSUE THREAD

**Issue by neeharv** [sergiodxa/react-lazy-image#5]
A common use case for lazyloading is also to do deferred loading of images - i.e, load a small thumbnail / blurry image first and in the background load the actual image up.

This logic is distinct from the viewport calculation one, and may or may not need it. Does it therefore make sense to split this into two components, something like

```js
<LazyLoadWhenInViewport>
  <LazyImage />
</LazyLoadWhenInViewport>
```

So that one can directly use `<LazyImage>` without using the layout code if needed. Since the hooks for when to trigger the lazy loading are present in `<LazyImage>`, this could potentially allow more robust parent components to be used for a variety of use cases.

**Comment by sergiodxa** [comment]
I think you can already do this setting a custom `defaultSource` prop.

You can set a **URL** or **base64** string as `defaultSource`, so instead of letting it empty if you pass the URL for the blurred low quality version of the image you are going to render that image.

When the image is in the viewport (or near to them if you set the `offset`) then this component it's going to start the download of the actual image y change the blurred one for the real one.

**Comment by Eruant** [comment]
Is is possible to have add something to target with `css`?

For example setting `defaultSource` to a small image (e.g. 16px big) which is then blurred with `css`. This class can then be removed (and therefor the blur is also removed).
```css
.lazy-loading {
  filter: blur(10px);
}
```

**Comment by sergiodxa** [comment]
@Eruant you can use `className` without problems
https://github.com/sergiodxa/react-lazy-image#common-img-attributes

**Comment by Eruant** [comment]
@sergiodxa  I know I can use `className` - but my use case would be to have a class that was **only** when the image had not been loaded.

**Comment by sergiodxa** [comment]
Use onLoadEnd to know when the image has finishing loading and remove the className.
